### ISSUE TITLE
Composer Support

### ISSUE THREAD

**Issue by sprankhub** [prakash282/OrderAttachment#1]
Thanks for the extension!

Could you add a `composer.json` and submit the extension to https://packagist.org?

**Comment by sprankhub** [comment]
I now saw that there is a `composer.json` in a subdirectory: https://github.com/prakash282/OrderAttachment/blob/master/Sp/Orderattachment/composer.json. Following suggestions:

1. It may make sense to use a more unique identifier than `sp`. `sp` seems to be used by others already: https://packagist.org/?query=sp%2F.
2. I suggest to skip the directories `Sp/Orderattachment` and directly add the code into the root of the repository. Otherwise, Packagist / Composer will not work correctly.

**Comment by mageprakash** [comment]
I have updated composer.

**Comment by mageprakash** [comment]
I have added the extension into packagist.org so you can download with composer now.

**composer require prakash282/orderattachment**

**Comment by sprankhub** [comment]
Thanks @prakash282!
