### ISSUE TITLE
Backend Users With Restricted Accounts Cannot Upload Attachments

### ISSUE THREAD

**Issue by sprankhub** [prakash282/OrderAttachment#12]
In the controllers, you define an `ADMIN_RESOURCE`, which is good:

https://github.com/prakash282/OrderAttachment/blob/88e921d0b7fe94c7637b77a215ea86191db3c115/Controller/Adminhtml/Attachment/Upload.php#L9

However, this resource is not defined anywhere. Hence, only full admin accounts can upload images. The used resources need to be defined in `etc/acl.xml`, so that they can be configured correctly.

**Comment by BorisovskiP** [comment]
PR provided for the fix : https://github.com/prakash282/OrderAttachment/pull/14

**Comment by sprankhub** [comment]
Fixed in #16.

**Comment by mageprakash** [comment]
Thank you Borisovskip for contribution
